/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.workshop;

import org.junit.Test;

import com.workshop.Executor;

import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testSomeLibraryMethod() {
        Executor classUnderTest = new Executor();
        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
    }
}
